# Generated by Django 2.1.7 on 2019-02-14 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20190214_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='date_reported',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
